### ISSUE TITLE
final storage$ overwrites the one from componentSinks

### ISSUE THREAD

**Issue by lopsch** [maiermic/cycle-storageify#3]
Hi there,

maybe I'm wrong but shouldn't it be something like
```
...
const stateStorage$ = state$.map(_options.serialize)
  .map(value => ({key: _options.key, value}));

const storage$ = componentSinks.storage
  ? xs.merge(stateStorage$, componentSinks.storage)
  : stateStorage$
```

Otherwise if there is already a `componentSinks.storage` it would just be replaced not augmented?

**Comment by maiermic** [comment]
I guess you're right. Even though I think that this is a rare case. The state of your component is already stored. So why should your component store something else?

**Comment by lopsch** [comment]
Good question ;-).
