### ISSUE TITLE
The second and third options should be declared as optional

### ISSUE THREAD

**Issue by SteveALee** [maiermic/cycle-storageify#4]
https://github.com/maiermic/cycle-storageify/blob/master/src/index.ts#L34-L35

as hard to use from TypeScript

I had to declare a type for the structure and cast it.

**Comment by maiermic** [comment]
Do you use the defaults or custom `serialize` and `deserialize` functions? Could you please give an example that requires a cast?

**Comment by SteveALee** [comment]
Sure

If anyone is interested here is a cyclejs SPA template - https://github.com/SteveALee/cycle-spa-template/blob/master/src/index.ts#L10-L19

I basically just copied the readme but it broke. Perhaps as I'm using strict TS mode.
