### ISSUE TITLE
XStream should be a peerDependency

### ISSUE THREAD

**Issue by geovanisouza92** [maiermic/cycle-storageify#9]
Related to https://github.com/cyclejs-community/create-cycle-app/issues/117

Projects created using CCA and `cycle-scripts-one-fits-all` include xstream twice: as a high-level dependency and for cycle-storageify. So, could you consider to move it to a peerDependency, helping on reducing the bundle size?

Thanks.

**Comment by maiermic** [comment]
Released in version 4.0.0
